/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/apple/iphonex/fullBody.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fullBody.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.371, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.37, 0]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.Metal} position={[-0.142, 0.092, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.flash} position={[0.096, 0.213, -0.019]} rotation={[Math.PI / 2, 0, 0]} />
            <group position={[0.096, 0.213, -0.019]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Object_18.geometry} material={materials.flash} position={[0, -0.001, 0]} />
              <mesh geometry={nodes.Object_21.geometry} material={materials.Metal} position={[0, -0.001, 0]} />
              <mesh geometry={nodes.Object_24.geometry} material={materials.glass} position={[0, -0.001, 0]} />
              <mesh geometry={nodes.Object_27.geometry} material={materials.glass_blue} position={[0, 0.003, 0.028]} />
              <mesh geometry={nodes.Object_15.geometry} material={materials.black_plastic} />
            </group>
            <mesh geometry={nodes.Object_48.geometry} material={materials.glass} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.Object_51.geometry} material={materials.glass_blue} position={[0.043, 0.261, 0.011]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.Metal_flat} position={[-0.027, -0.283, 0]} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.white_plastic} />
            <group position={[0.14, -0.016, 0]}>
              <mesh geometry={nodes.Object_39.geometry} material={materials.Metal} position={[-0.002, -0.02, 0]} rotation={[0, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Object_36.geometry} material={materials.Metal} />
            </group>
            <mesh geometry={nodes.Object_42.geometry} material={materials.Metal} position={[0.141, 0.119, 0]} />
            <mesh geometry={nodes.Object_33.geometry} material={materials['Metal.frame']} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.black_plastic} />
            <mesh geometry={nodes.Object_54.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.Metal_flat} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fullBody.glb')
